# Generated by Django 4.2.6 on 2023-11-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=250)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_subject', models.TextField()),
            ],
        ),
    ]
